name: Marcelo Mendoza
description: 
meta_description: "Marcelo Mendoza"

markdown: redcarpet
pygments: true

baseurl: http://mjmendo.github.io/

logo: false
paginate: 15
permalink: /:title


# Details for the RSS feed generator
url:            'mjmendo.github.io'
author:         'Marcelo Mendoza'


